"""Models for auto-scaling recommendations and cost analysis."""

from __future__ import annotations

from datetime import UTC, datetime
from enum import StrEnum
from typing import Any

from pydantic import BaseModel, Field


class AlertSeverity(StrEnum):
    """Severity of a cost alert."""

    INFO = "info"
    WARNING = "warning"
    CRITICAL = "critical"


class RecommendationType(StrEnum):
    """Category of a usage recommendation."""

    COST_SAVING = "cost_saving"
    PERFORMANCE = "performance"
    SCALING = "scaling"
    MODEL_SWITCH = "model_switch"


class TrafficSnapshot(BaseModel):
    """A snapshot of traffic metrics for a specific model/provider.

    Stored periodically by :class:`TrafficAnalyser` to enable
    trend-based analysis and scaling recommendations.
    """

    model: str
    timestamp: datetime = Field(default_factory=lambda: datetime.now(tz=UTC))
    requests_per_minute: float = 0.0
    tokens_per_minute: float = 0.0
    avg_latency_ms: float = 0.0
    error_rate: float = 0.0
    total_cost: float = 0.0
    total_requests: int = 0
    total_tokens: int = 0


class UsageRecommendation(BaseModel):
    """A single actionable recommendation.

    Generated by the :class:`RecommendationEngine` based on traffic
    patterns and cost analysis.
    """

    rec_type: RecommendationType
    title: str
    description: str
    model: str | None = None
    suggested_model: str | None = None
    estimated_savings_pct: float = 0.0
    estimated_savings_usd: float = 0.0
    confidence: float = Field(default=0.5, ge=0.0, le=1.0)
    metadata: dict[str, Any] = Field(default_factory=dict)


class CostAlert(BaseModel):
    """A cost alert triggered when spend thresholds are breached."""

    severity: AlertSeverity
    title: str
    description: str
    model: str | None = None
    current_spend: float = 0.0
    threshold: float = 0.0
    timestamp: datetime = Field(default_factory=lambda: datetime.now(tz=UTC))
    metadata: dict[str, Any] = Field(default_factory=dict)


class ModelCostProfile(BaseModel):
    """Cost profile for a model used in optimization analysis."""

    model: str
    provider: str = ""
    input_cost_per_token: float = 0.0
    output_cost_per_token: float = 0.0
    avg_latency_ms: float = 0.0
    quality_score: float = Field(default=0.5, ge=0.0, le=1.0)


class CostThreshold(BaseModel):
    """A configured spend threshold that triggers an alert."""

    name: str
    amount: float
    period: str = Field(
        default="daily",
        description="daily | weekly | monthly",
    )
    severity: AlertSeverity = AlertSeverity.WARNING
    model: str | None = Field(
        default=None,
        description="If set, threshold applies to this model only.",
    )
    enabled: bool = True


class ScalingConfig(BaseModel):
    """Top-level configuration for auto-scaling recommendations."""

    enabled: bool = False
    snapshot_interval_seconds: int = Field(
        default=60,
        description="How often to capture traffic snapshots.",
    )
    max_snapshots: int = Field(
        default=1440,
        description="Maximum snapshots to retain (default: 24h at 1/min).",
    )
    cost_thresholds: list[CostThreshold] = Field(default_factory=list)
    alternative_models: list[ModelCostProfile] = Field(
        default_factory=list,
        description="Models to consider for cost optimization suggestions.",
    )
    enable_cost_alerts: bool = True
    enable_recommendations: bool = True
