"""initial schema

Revision ID: c720cc74f9df
Revises: 
Create Date: 2026-08-12 23:17:06.407684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c720cc74f9df'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('actor_type', sa.String(length=32), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=True),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_logs_actor_action', 'audit_logs', ['actor_id', 'action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_target_type'), 'audit_logs', ['target_type'], unique=False)
    op.create_table('model_configs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=128), nullable=False),
    sa.Column('api_base', sa.Text(), nullable=True),
    sa.Column('api_key_encrypted', sa.Text(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_configs_model_name'), 'model_configs', ['model_name'], unique=True)
    op.create_table('teams',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('budget_limit', sa.Float(), nullable=True),
    sa.Column('spend', sa.Float(), nullable=False),
    sa.Column('max_budget_per_member', sa.Float(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_name'), 'teams', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('max_budget', sa.Float(), nullable=True),
    sa.Column('spend', sa.Float(), nullable=False),
    sa.Column('sso_provider_id', sa.String(length=255), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index('ix_users_sso_provider_id', 'users', ['sso_provider_id'], unique=False)
    op.create_table('user_teams',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'team_id')
    )
    op.create_table('virtual_keys',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('key_prefix', sa.String(length=16), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('team_id', sa.Uuid(), nullable=True),
    sa.Column('models', sa.JSON(), nullable=False),
    sa.Column('max_budget', sa.Float(), nullable=True),
    sa.Column('spend', sa.Float(), nullable=False),
    sa.Column('rate_limit_rpm', sa.Integer(), nullable=True),
    sa.Column('rate_limit_tpm', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_virtual_keys_key_hash'), 'virtual_keys', ['key_hash'], unique=True)
    op.create_index(op.f('ix_virtual_keys_team_id'), 'virtual_keys', ['team_id'], unique=False)
    op.create_index(op.f('ix_virtual_keys_user_id'), 'virtual_keys', ['user_id'], unique=False)
    op.create_index('ix_virtual_keys_user_team', 'virtual_keys', ['user_id', 'team_id'], unique=False)
    op.create_table('guardrail_policies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=True),
    sa.Column('key_id', sa.Uuid(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['key_id'], ['virtual_keys.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guardrail_policies_key_id'), 'guardrail_policies', ['key_id'], unique=False)
    op.create_index(op.f('ix_guardrail_policies_team_id'), 'guardrail_policies', ['team_id'], unique=False)
    op.create_table('spend_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('key_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('team_id', sa.Uuid(), nullable=True),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=128), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('tokens_prompt', sa.Integer(), nullable=False),
    sa.Column('tokens_completion', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['key_id'], ['virtual_keys.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spend_logs_created_at'), 'spend_logs', ['created_at'], unique=False)
    op.create_index('ix_spend_logs_created_model', 'spend_logs', ['created_at', 'model'], unique=False)
    op.create_index(op.f('ix_spend_logs_key_id'), 'spend_logs', ['key_id'], unique=False)
    op.create_index(op.f('ix_spend_logs_model'), 'spend_logs', ['model'], unique=False)
    op.create_index(op.f('ix_spend_logs_request_id'), 'spend_logs', ['request_id'], unique=False)
    op.create_index(op.f('ix_spend_logs_team_id'), 'spend_logs', ['team_id'], unique=False)
    op.create_index(op.f('ix_spend_logs_user_id'), 'spend_logs', ['user_id'], unique=False)
    op.create_index('ix_spend_logs_user_team', 'spend_logs', ['user_id', 'team_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_spend_logs_user_team', table_name='spend_logs')
    op.drop_index(op.f('ix_spend_logs_user_id'), table_name='spend_logs')
    op.drop_index(op.f('ix_spend_logs_team_id'), table_name='spend_logs')
    op.drop_index(op.f('ix_spend_logs_request_id'), table_name='spend_logs')
    op.drop_index(op.f('ix_spend_logs_model'), table_name='spend_logs')
    op.drop_index(op.f('ix_spend_logs_key_id'), table_name='spend_logs')
    op.drop_index('ix_spend_logs_created_model', table_name='spend_logs')
    op.drop_index(op.f('ix_spend_logs_created_at'), table_name='spend_logs')
    op.drop_table('spend_logs')
    op.drop_index(op.f('ix_guardrail_policies_team_id'), table_name='guardrail_policies')
    op.drop_index(op.f('ix_guardrail_policies_key_id'), table_name='guardrail_policies')
    op.drop_table('guardrail_policies')
    op.drop_index('ix_virtual_keys_user_team', table_name='virtual_keys')
    op.drop_index(op.f('ix_virtual_keys_user_id'), table_name='virtual_keys')
    op.drop_index(op.f('ix_virtual_keys_team_id'), table_name='virtual_keys')
    op.drop_index(op.f('ix_virtual_keys_key_hash'), table_name='virtual_keys')
    op.drop_table('virtual_keys')
    op.drop_table('user_teams')
    op.drop_index('ix_users_sso_provider_id', table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_teams_name'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_model_configs_model_name'), table_name='model_configs')
    op.drop_table('model_configs')
    op.drop_index(op.f('ix_audit_logs_target_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_actor_action', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
