"""Core Pydantic models for OpenAI-compatible request/response types.

These models mirror the OpenAI API format exactly so that RouterBot can act
as a transparent proxy. All request models use ``extra="allow"`` to support
provider-specific passthrough fields.
"""

from __future__ import annotations

import time
import uuid
from typing import Any, Literal

from pydantic import BaseModel, Field

from routerbot.core.enums import (
    AudioResponseFormat,
    AudioVoice,
    EmbeddingEncodingFormat,
    FinishReason,
    ImageQuality,
    ImageResponseFormat,
    ImageSize,
    ImageStyle,
    Role,
)

# ---------------------------------------------------------------------------
# Shared / building-block types
# ---------------------------------------------------------------------------


class FunctionCall(BaseModel):
    """A function call generated by the model (deprecated path)."""

    name: str
    arguments: str  # JSON-encoded string

    model_config = {"extra": "allow"}


class Function(BaseModel):
    """Function definition within a tool."""

    name: str
    description: str | None = None
    parameters: dict[str, Any] | None = None
    strict: bool | None = None

    model_config = {"extra": "allow"}


class ToolCall(BaseModel):
    """A tool call generated by the model."""

    id: str = Field(default_factory=lambda: f"call_{uuid.uuid4().hex[:24]}")
    type: Literal["function"] = "function"
    function: FunctionCall

    model_config = {"extra": "allow"}


class Tool(BaseModel):
    """Tool definition passed in a request."""

    type: Literal["function"] = "function"
    function: Function

    model_config = {"extra": "allow"}


class ResponseFormatText(BaseModel):
    """Response format: plain text."""

    type: Literal["text"] = "text"


class ResponseFormatJsonObject(BaseModel):
    """Response format: JSON object."""

    type: Literal["json_object"] = "json_object"


class ResponseFormatJsonSchema(BaseModel):
    """Response format: structured JSON schema."""

    type: Literal["json_schema"] = "json_schema"
    json_schema: dict[str, Any]


ResponseFormat = ResponseFormatText | ResponseFormatJsonObject | ResponseFormatJsonSchema


class StreamOptions(BaseModel):
    """Options for streaming responses."""

    include_usage: bool | None = None


# ---------------------------------------------------------------------------
# Message types
# ---------------------------------------------------------------------------


class ContentPartText(BaseModel):
    """Text content part within a multi-modal message."""

    type: Literal["text"] = "text"
    text: str


class ImageUrl(BaseModel):
    """Image URL reference within a content part."""

    url: str
    detail: str | None = None


class ContentPartImage(BaseModel):
    """Image content part within a multi-modal message."""

    type: Literal["image_url"] = "image_url"
    image_url: ImageUrl


class InputAudio(BaseModel):
    """Inline audio data within a content part."""

    data: str  # base64-encoded audio
    format: str  # e.g. "wav", "mp3"


class ContentPartInputAudio(BaseModel):
    """Audio content part within a multi-modal message."""

    type: Literal["input_audio"] = "input_audio"
    input_audio: InputAudio


ContentPart = ContentPartText | ContentPartImage | ContentPartInputAudio


class Message(BaseModel):
    """A single message in a conversation.

    ``content`` may be a plain string or a list of content parts for
    multi-modal inputs (text + image + audio).
    """

    role: Role
    content: str | list[ContentPart] | None = None
    name: str | None = None
    tool_calls: list[ToolCall] | None = None
    tool_call_id: str | None = None
    function_call: FunctionCall | None = None  # deprecated
    refusal: str | None = None

    model_config = {"extra": "allow"}


# ---------------------------------------------------------------------------
# Usage / token details
# ---------------------------------------------------------------------------


class PromptTokensDetails(BaseModel):
    """Breakdown of prompt token counts."""

    cached_tokens: int = 0
    audio_tokens: int = 0


class CompletionTokensDetails(BaseModel):
    """Breakdown of completion token counts."""

    reasoning_tokens: int = 0
    audio_tokens: int = 0
    accepted_prediction_tokens: int = 0
    rejected_prediction_tokens: int = 0


class Usage(BaseModel):
    """Token usage statistics for a completion."""

    prompt_tokens: int = 0
    completion_tokens: int = 0
    total_tokens: int = 0
    prompt_tokens_details: PromptTokensDetails | None = None
    completion_tokens_details: CompletionTokensDetails | None = None


# ---------------------------------------------------------------------------
# Chat Completion — Request
# ---------------------------------------------------------------------------


class CompletionRequest(BaseModel):
    """OpenAI-compatible ``/chat/completions`` request body.

    Uses ``extra="allow"`` so that provider-specific or future fields pass
    through untouched.
    """

    model: str
    messages: list[Message]

    # Sampling parameters
    temperature: float | None = None
    top_p: float | None = None
    n: int | None = None
    stream: bool | None = None
    stream_options: StreamOptions | None = None
    stop: str | list[str] | None = None
    max_tokens: int | None = None  # deprecated, use max_completion_tokens
    max_completion_tokens: int | None = None
    presence_penalty: float | None = None
    frequency_penalty: float | None = None
    logit_bias: dict[str, float] | None = None
    logprobs: bool | None = None
    top_logprobs: int | None = None
    seed: int | None = None

    # Tool / function calling
    tools: list[Tool] | None = None
    tool_choice: str | dict[str, Any] | None = None
    parallel_tool_calls: bool | None = None
    functions: list[Function] | None = None  # deprecated
    function_call: str | dict[str, Any] | None = None  # deprecated

    # Response format
    response_format: ResponseFormat | None = None

    # Misc
    user: str | None = None
    metadata: dict[str, str] | None = None
    store: bool | None = None
    service_tier: str | None = None
    reasoning_effort: str | None = None

    model_config = {"extra": "allow"}


# ---------------------------------------------------------------------------
# Chat Completion — Response
# ---------------------------------------------------------------------------


class TopLogprob(BaseModel):
    """A single top-logprob entry."""

    token: str
    logprob: float
    bytes: list[int] | None = None


class TokenLogprob(BaseModel):
    """Log probability info for a single token."""

    token: str
    logprob: float
    bytes: list[int] | None = None
    top_logprobs: list[TopLogprob] = Field(default_factory=list)


class ChoiceLogprobs(BaseModel):
    """Logprobs container for a choice."""

    content: list[TokenLogprob] | None = None
    refusal: list[TokenLogprob] | None = None


class ChoiceMessage(BaseModel):
    """The assistant message inside a choice."""

    role: Role = Role.ASSISTANT
    content: str | None = None
    refusal: str | None = None
    tool_calls: list[ToolCall] | None = None
    function_call: FunctionCall | None = None  # deprecated
    annotations: list[Any] = Field(default_factory=list)

    model_config = {"extra": "allow"}


class Choice(BaseModel):
    """A single completion choice."""

    index: int = 0
    message: ChoiceMessage
    finish_reason: FinishReason | None = None
    logprobs: ChoiceLogprobs | None = None

    model_config = {"extra": "allow"}


class CompletionResponse(BaseModel):
    """OpenAI-compatible ``/chat/completions`` response.

    The ``id`` and ``created`` fields are auto-populated with sensible
    defaults when not provided (useful for provider adapters that need to
    construct responses).
    """

    id: str = Field(default_factory=lambda: f"chatcmpl-{uuid.uuid4().hex[:29]}")
    object: Literal["chat.completion"] = "chat.completion"
    created: int = Field(default_factory=lambda: int(time.time()))
    model: str = ""
    choices: list[Choice] = Field(default_factory=list)
    usage: Usage | None = None
    system_fingerprint: str | None = None
    service_tier: str | None = None

    model_config = {"extra": "allow"}


# ---------------------------------------------------------------------------
# Chat Completion — Streaming chunk
# ---------------------------------------------------------------------------


class DeltaMessage(BaseModel):
    """Partial message delta in a streaming chunk."""

    role: Role | None = None
    content: str | None = None
    tool_calls: list[ToolCall] | None = None
    function_call: FunctionCall | None = None  # deprecated
    refusal: str | None = None

    model_config = {"extra": "allow"}


class ChunkChoice(BaseModel):
    """A single choice within a streaming chunk."""

    index: int = 0
    delta: DeltaMessage = Field(default_factory=DeltaMessage)
    finish_reason: FinishReason | None = None
    logprobs: ChoiceLogprobs | None = None

    model_config = {"extra": "allow"}


class CompletionResponseChunk(BaseModel):
    """OpenAI-compatible streaming chunk for ``/chat/completions``."""

    id: str = Field(default_factory=lambda: f"chatcmpl-{uuid.uuid4().hex[:29]}")
    object: Literal["chat.completion.chunk"] = "chat.completion.chunk"
    created: int = Field(default_factory=lambda: int(time.time()))
    model: str = ""
    choices: list[ChunkChoice] = Field(default_factory=list)
    usage: Usage | None = None
    system_fingerprint: str | None = None
    service_tier: str | None = None

    model_config = {"extra": "allow"}


# ---------------------------------------------------------------------------
# Embedding — Request / Response
# ---------------------------------------------------------------------------


class EmbeddingRequest(BaseModel):
    """OpenAI-compatible ``/embeddings`` request body."""

    model: str
    input: str | list[str] | list[int] | list[list[int]]
    encoding_format: EmbeddingEncodingFormat | None = None
    dimensions: int | None = None
    user: str | None = None

    model_config = {"extra": "allow"}


class EmbeddingData(BaseModel):
    """A single embedding vector."""

    object: Literal["embedding"] = "embedding"
    index: int = 0
    embedding: list[float] | str  # float list or base64 string


class EmbeddingUsage(BaseModel):
    """Token usage for an embedding request."""

    prompt_tokens: int = 0
    total_tokens: int = 0


class EmbeddingResponse(BaseModel):
    """OpenAI-compatible ``/embeddings`` response."""

    object: Literal["list"] = "list"
    data: list[EmbeddingData] = Field(default_factory=list)
    model: str = ""
    usage: EmbeddingUsage = Field(default_factory=EmbeddingUsage)

    model_config = {"extra": "allow"}


# ---------------------------------------------------------------------------
# Image Generation — Request / Response
# ---------------------------------------------------------------------------


class ImageRequest(BaseModel):
    """OpenAI-compatible ``/images/generations`` request body."""

    model: str = "dall-e-3"
    prompt: str
    n: int | None = 1
    size: ImageSize | None = None
    quality: ImageQuality | None = None
    style: ImageStyle | None = None
    response_format: ImageResponseFormat | None = None
    user: str | None = None

    model_config = {"extra": "allow"}


class ImageData(BaseModel):
    """A single generated image."""

    url: str | None = None
    b64_json: str | None = None
    revised_prompt: str | None = None


class ImageResponse(BaseModel):
    """OpenAI-compatible ``/images/generations`` response."""

    created: int = Field(default_factory=lambda: int(time.time()))
    data: list[ImageData] = Field(default_factory=list)

    model_config = {"extra": "allow"}


# ---------------------------------------------------------------------------
# Audio — Speech (TTS) Request / Response
# ---------------------------------------------------------------------------


class AudioSpeechRequest(BaseModel):
    """OpenAI-compatible ``/audio/speech`` request body."""

    model: str = "tts-1"
    input: str
    voice: AudioVoice = AudioVoice.ALLOY
    response_format: AudioResponseFormat | None = None
    speed: float | None = None

    model_config = {"extra": "allow"}


# Audio speech response is raw binary, no model needed.


# ---------------------------------------------------------------------------
# Audio — Transcription Request / Response
# ---------------------------------------------------------------------------


class AudioTranscriptionRequest(BaseModel):
    """OpenAI-compatible ``/audio/transcriptions`` request body.

    Note: the actual ``file`` field is handled as form data at the proxy
    layer; this model covers the non-file parameters only.
    """

    model: str = "whisper-1"
    language: str | None = None
    prompt: str | None = None
    response_format: str | None = None  # json, text, srt, verbose_json, vtt
    temperature: float | None = None
    timestamp_granularities: list[str] | None = None

    model_config = {"extra": "allow"}


class AudioTranscriptionResponse(BaseModel):
    """OpenAI-compatible transcription response (JSON mode)."""

    text: str

    model_config = {"extra": "allow"}


# ---------------------------------------------------------------------------
# Rerank — Request / Response (Cohere-style, growing ecosystem support)
# ---------------------------------------------------------------------------


class RerankRequest(BaseModel):
    """Rerank request (Cohere/Jina compatible)."""

    model: str
    query: str
    documents: list[str] | list[dict[str, Any]]
    top_n: int | None = None
    return_documents: bool | None = None

    model_config = {"extra": "allow"}


class RerankResult(BaseModel):
    """A single reranked document."""

    index: int
    relevance_score: float
    document: dict[str, Any] | None = None


class RerankResponse(BaseModel):
    """Rerank response."""

    id: str = Field(default_factory=lambda: f"rerank-{uuid.uuid4().hex[:24]}")
    results: list[RerankResult] = Field(default_factory=list)
    model: str = ""
    usage: EmbeddingUsage | None = None

    model_config = {"extra": "allow"}


# ---------------------------------------------------------------------------
# Model Info — metadata registry entry
# ---------------------------------------------------------------------------


class ModelCard(BaseModel):
    """Model metadata as returned by ``/models`` and used in the registry.

    This is the runtime model info (distinct from the config-level
    ``ModelInfo`` used in ``routerbot_config.yaml``).
    """

    id: str
    object: Literal["model"] = "model"
    created: int = Field(default_factory=lambda: int(time.time()))
    owned_by: str = "routerbot"
    max_input_tokens: int | None = None
    max_output_tokens: int | None = None
    input_cost_per_token: float | None = None
    output_cost_per_token: float | None = None
    supports_vision: bool = False
    supports_function_calling: bool = False
    supports_streaming: bool = True
    context_window: int | None = None

    model_config = {"extra": "allow"}


class ModelListResponse(BaseModel):
    """OpenAI-compatible ``/models`` list response."""

    object: Literal["list"] = "list"
    data: list[ModelCard] = Field(default_factory=list)
